In [4]:
import numpy as np 
a = np.array([1,2,3,4]).reshape(2,2)
b = np.array([5,6,7,8]).reshape(2,2)

In [5]:
a

array([[1, 2],
       [3, 4]])

In [6]:
b

array([[5, 6],
       [7, 8]])

In [7]:
a+b #will return the sum (same as matrices)

array([[ 6,  8],
       [10, 12]])

In [8]:
a-b #will return the difference (same as matrices)

array([[-4, -4],
       [-4, -4]])

In [9]:
a*b #will return the multiplication  (elelement by element Scalar multilpication not like matrices)

array([[ 5, 12],
       [21, 32]])

In [10]:
a.dot(b) #will return the Multiplication (same as matrices)

array([[19, 22],
       [43, 50]])