In [2]:
import numpy as np
a = np.array([1,2,3,4,5])
a*2 #multiply each element with 2

array([ 2,  4,  6,  8, 10])

In [3]:
import numpy as np
a = np.array([1,2,3,4,5])
a+2 #add each element with 2

array([3, 4, 5, 6, 7])

In [5]:
import numpy as np
a = np.array([1,2,3,4,5])
a/2 #divide each element with 2

array([0.5, 1. , 1.5, 2. , 2.5])

In [6]:
import numpy as np
a = np.array([1,2,3,4,5])
a**2 #take square of each element

array([ 1,  4,  9, 16, 25], dtype=int32)

In [7]:
import numpy as np
a = np.array([1,2,3,4,5])
a**3 #take cube of each element

array([  1,   8,  27,  64, 125], dtype=int32)

In [9]:
import numpy as np
a = np.array([1,2,3,4,0])
a/0 #division by zero is not error but infinity

C:\Users\H\AppData\Local\Temp/ipykernel_13868/1928165452.py:3: RuntimeWarning: divide by zero encountered in true_divide
  a/0 #division by zero is not error but infinity
C:\Users\H\AppData\Local\Temp/ipykernel_13868/1928165452.py:3: RuntimeWarning: invalid value encountered in true_divide
  a/0 #division by zero is not error but infinity


array([inf, inf, inf, inf, nan])