In [1]:
import numpy as np
np.random.seed(121)
matrix = np.random.randint(1,21,9).reshape(3,3)
matrix

array([[ 3,  9,  2],
       [20,  1, 15],
       [ 3,  4, 10]])

In [2]:
np.max(matrix)

20

In [3]:
np.min(matrix)

1

In [4]:
np.sum(matrix)

67

In [5]:
np.max(matrix,axis=1) #axis 1 ka mtlb row wise finding aur axis 0 ka mtlb column wise finding

array([ 9, 20, 10])

In [6]:
np.max(matrix,axis=0)

array([3, 1, 2])

In [7]:
np.min(matrix,axis=1)

array([2, 1, 3])

In [8]:
np.min(matrix,axis=0)

array([3, 1, 2])

In [9]:
np.sum(matrix,axis=1)

array([14, 36, 17])

In [10]:
np.sum(matrix,axis=0)

array([26, 14, 27])

In [11]:
np.cumsum(matrix) #cum sum main first value aisay hi ayegi second first aur second ka sum third 1st 2nd aur 3rd ka sum and so on...

array([ 3, 12, 14, 34, 35, 50, 53, 57, 67], dtype=int32)