In [3]:
import numpy as np
myArr = np.zeros(5) #zeros 1D (vector)
myArr2 = np.zeros((2,3)) #zeros 2D --> ismay coordinate dete hain 2,3 means 2 rows 3 columns (matrix)
myArr
myArr2

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
import numpy as np
myArr = np.ones(5) #ones 1D (vector)
myArr2 = np.ones((4,1)) #zeros 2D --> (matrix of 4,1 order)
myArr
myArr2

array([[1.],
       [1.],
       [1.],
       [1.]])

In [9]:
import numpy as np
myArr = np.eye(5) #eye method aik identity matrix (jiska principal diagonal 1 houta hai aur baaki elements zero houtay hain return karega)
# identity matrix aik square matrix houta hai tou 5 ka mtlb 5,5 5X5 hoga..

myArr
# but eye is beyond the limits of square matrix so ager irregular yani rectangular matrix dia jayega tou jahan tk banega diagonal wahan tk 1's ayengay aagay zeros

myArr2 = np.eye(3,4)
myArr2

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [11]:
import numpy as np
myArr = np.diag([1,2,3,4]) #diag --> aik matrix(2D array) return krta hai jo aik 1d array(vector) expect krta hai is ko principal diagonal banata hai aur return krta hai diagonal matrix
myArr

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [14]:
import numpy as np
myArr = np.random.randint(1,10,3) #random.randint(startingRange,endingrange+1,noOfValuesyouWantInArray)
myArr

array([4, 4, 5])

In [18]:
import numpy as np
myArr = np.random.rand(5) #yeh 0-1 k darmiyaan koi value return krta hai each index k liayy jese yahan 0-1 k darmiyaan 5 values return hongi
myArr

#isko 2D array k liay bhi kia jaskta hai
myArr2 = np.random.rand(3,4) # yahan tuple main nhi dena ! remember it!
myArr2

array([[0.5010438 , 0.75003971, 0.54159937, 0.24655536],
       [0.6449142 , 0.64876173, 0.19732856, 0.13080946],
       [0.09659713, 0.32023157, 0.83885929, 0.87659828]])

In [20]:
import numpy as np
myArr = np.random.randn(5)
# random.randn return krta hai 0 se qareeb qareeb values jo positive and negative dono hoskti hain.
myArr

array([-0.2614886 ,  0.77230177,  0.27600912, -0.79321874,  0.42326923])