In [1]:
#question 1
import numpy as np

In [2]:
#question 2
import numpy as np
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [3]:
#question 3
import numpy as np
arr = np.random.randint(1,101,10)
arr

array([51, 38, 53, 93, 28, 14,  7, 27, 63, 44])

In [6]:
#question 4

import numpy as np
arr = np.arange(10,21)
arr


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [7]:
#question 5
import numpy as np
arr = np.ones(10)
arr*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [8]:
#question 6
import numpy as np
arr = np.random.randint(1,21,9).reshape(3,3)
arr

array([[ 7, 16, 11],
       [15,  9, 12],
       [17,  1,  1]])

In [10]:
#question 7
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10])
arr[arr%2==0] = 0
arr

array([1, 0, 3, 0, 5, 0, 7, 0, 9, 0])

In [11]:
#question 8
import numpy as np
arr = np.random.rand(9).reshape(3,3)
arr

array([[0.50122351, 0.52094386, 0.75697409],
       [0.13180667, 0.96402611, 0.77047796],
       [0.95056525, 0.2620533 , 0.03676952]])