In [5]:
import numpy as np
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
np.hstack((arr1,arr2)) #pehli array tou aisay hi ayegi , second array ko horizontally stack krdega

array([1, 2, 3, 4, 5, 6, 7, 8])

In [6]:
import numpy as np
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
np.vstack((arr1,arr2)) #pehli array tou aisay hi ayegi , second array ko vertically stack krdega wrt to first one 

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [7]:
#yeh saara kaam 2D array (matrix) main bhi hoskta hai.
import numpy as np
np.random.seed(123)
arr3 = np.random.randint(1,21,9).reshape(3,3)
arr4 = np.random.randint(51,71,9).reshape(3,3)
np.hstack((arr3,arr4))

array([[14,  3,  3, 68, 66, 60],
       [ 7, 18, 20, 51, 65, 51],
       [11,  2,  1, 66, 70, 65]])

In [8]:
import numpy as np
np.random.seed(123)
arr3 = np.random.randint(1,21,9).reshape(3,3)
arr4 = np.random.randint(51,71,9).reshape(3,3)
np.vstack((arr3,arr4))

array([[14,  3,  3],
       [ 7, 18, 20],
       [11,  2,  1],
       [68, 66, 60],
       [51, 65, 51],
       [66, 70, 65]])